modLoader="javafml"
loaderVersion="[47,)"
license="LGPL-3.0-only"
issueTrackerURL="https://github.com/Raishxn/GTO-Additions/issues"
[[mods]]
modId="gtoa"
version="${version}"
displayName="GTO-Additions"
authors="Raishxn"
displayURL="https://github.com/Raishxn/GTO-Additions"
description="Additional machines for GregTech Odyssey 0.6.0-dev9."
[[dependencies.gtoa]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.20.2)"
ordering="NONE"
side="BOTH"
[[dependencies.gtoa]]
modId="forge"
mandatory=true
versionRange="[47.4.20,48)"
ordering="NONE"
side="BOTH"
[[dependencies.gtoa]]
modId="gtceu"
mandatory=true
versionRange="[26.9.70,26.9.71)"
ordering="BEFORE"
side="BOTH"
[[dependencies.gtoa]]
modId="gtocore"
mandatory=true
versionRange="[26.9.5,26.9.6)"
ordering="BEFORE"
side="BOTH"
